name: Despliegue de Prueba

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar ambiente
      run: |
        # Instala las dependencias de Laravel
        composer install --no-dev

    - name: Configurar archivo .env
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Ejecutar pruebas
      run: php artisan test

    - name: Desplegar en GitHub Pages
      run: |
        # Agrega aquí los comandos para desplegar tu aplicación en GitHub Pages
        # Puedes generar un directorio de construcción y usar GitHub Pages para desplegar HTML, CSS, y JS
        php artisan build
        mkdir gh-pages
        cp -r * gh-pages/
        git checkout gh-pages
        git add .
        git commit -m "Despliegue de prueba"
        git push origin gh-pages

