name: Test de Despliegue

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar ambiente
      run: |
        # Instala las dependencias de Laravel
        composer install --no-dev

    - name: Configurar archivo .env
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Despliegue Exitoso
      run: |
       


